### ISSUE TITLE
出厂系统太臃肿，不支持ipv6，

### ISSUE THREAD

**Issue by f4nff** [R86S/R86S-QuickInstaller#1]
出厂系统太臃肿，而且有些openwrt默认路由表功能等无法使用。

尝试刷
[https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz)

但是没用2.5G网卡驱动。

建议厂家在openwrt 原版上面增加2.5G网卡驱动的img，其他不要动。

**Comment by ShireCiel** [comment]
集成很多组建的主要原因在于。出厂固件采用了与远领先于Openwrt官方的内核版本。
有很多内核组建是无法从官方的package源种获得内核相关的包。
故尽量集成了日常可能需要的功能包。
并且这些功能包的存在对系统运行速度是没有影响的。

**Comment by f4nff** [comment]
实际测试，集成了那些会出现bug，我直接刷了官方的包，搞了驱动，就没问题。
领先于官方的内核，为啥我用tun都没用，ipv6也是残废，

**Comment by f4nff** [comment]
我觉得，像你们这种，保持官方开发版就好了，非要搞什么定制，用户需要可以自己安装，而且你们自己搞得，基本没有怎么测试过，还集成ss openvpn，大陆官方是不允许吧，

**Comment by f4nff** [comment]
产品做的不错，从电源插头做工就可以看出，固件太拉垮，

**Comment by f4nff** [comment]
[https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz)

kmod-tun_5.10.100-1_x86_64.ipk
kmod-tcp-bbr_5.10.100-1_x86_64.ipk
kmod-igc_5.10.100-1_x86_64.ipk

我安装了官方的开发板，然后又安装了这几个，解决了驱动问题，
初次安装有点麻烦，但是安装好之后，正常使用没bug，
而你们出厂系统好多问题，r4s 虽然出厂也臃肿，但是基本使用ipv6 tun 这些没得问题，太拉跨，
你们可以搞2个版本，一个精简版，一个你们这种集成的。

**Comment by ShireCiel** [comment]
> ipv6 tun

ipv6 tun 这两个有啥问题。说一下。
这个是官方的？ 可以呀。官方上Linux5.10内核了。

**Comment by f4nff** [comment]
用你们提供的出厂固件
1：ipv6残废的。
2：tun2socks启动不起来，静态ipv4 ipv6路由功能都是残废，无效。

同样的程序，我使用r4s没问题，
使用r86s刷openwrt 官方开发版，也没问题，
然后我就没再测你们出厂固件了，
内置看到还要shadowsocks，openvpn什么的，不知道你们固件在哪搬的。

**Comment by f4nff** [comment]
一句话概括就是，
r86s我刷 [openwrt 开发版](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz)，5.10内核，没遇到什么bug，
但是r86s刷你们出厂的，也只能不操作进行一下简单的使用。

<img width="714" alt="image" src="https://user-images.githubusercontent.com/19538878/154884626-550cac8d-105a-4fcb-9386-063c4d71b905.png">

**Comment by f4nff** [comment]
我倒是建议你们在官方

https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz

kmod-tun_5.10.100-1_x86_64.ipk
kmod-tcp-bbr_5.10.100-1_x86_64.ipk
kmod-igc_5.10.100-1_x86_64.ipk

集成一下，然后就不要动了，用户使用什么，用户自己去安装，搞的很多，出问题的概率就大。

**Comment by ShireCiel** [comment]
> 内置看到还要shadowsocks，openvpn什么的，不知道你们固件在哪搬的。

请列举你要安装的所有包。 我这边检查一下兼容性。
官方的之所以能够随便下载 是因为 官方自动编译了几乎所有的 外部包并且有 CDN给你们下载这些包。

目前自制固件是没有这些条件的。 需要编译的时候就把包依赖弄好。特别是内核模块的包。

**Comment by f4nff** [comment]
什么也不需要，只需要最简化的openwrt即可。
