### ISSUE TITLE
Revert Back To Original

### ISSUE THREAD

**Issue by ex3xex** [R86S/R86S-QuickInstaller#3]
Hi,

When first time I receive my R86S, I went to install Windows 11 because I need to do something in there. Now I want to go back to OpenWRT, How can I do that? If I'm not mistaken you guys have provided the firmware file from here:

https://github.com/R86S/lede/releases/

But I need a proper guide how to install it to R86S internal emmc.

**Comment by ShireCiel** [comment]
Download factory openwrt.
There has a command for write to emmc.
r86s-write-this-to-emmc.sh

**Comment by ex3xex** [comment]
How to setup proper live usb boot to get the command executed successfully? Last time I've tried with Ubuntu but error when executed either `r86s-clean-emmc.sh` nor `r86s-write-this-to-emmc.sh`.

**Comment by ShireCiel** [comment]
These two command only exist in offical system.
You need download it from "https://github.com/R86S/lede/releases/".
And use refus write it to you udisk. 
F7 choose boot it. Run these command in offical system

**Comment by ex3xex** [comment]
Thanks, I'll give it a try and let you know soon.

**Comment by ex3xex** [comment]
As per your guide, I'm booting from R86s lede release image and run the command but the result still give me 'Resource busy' error. Here's the log:

```
root@OpenWrt:~/tmp/R86S-QuickInstaller/r86s-quick-installer/src# ./r86s-clean-emmc.sh
WARNING!!!!!!
Will Clean All Data On EMMC!!!
Enter "confirm" to contine!:
confirm
Will Clean All Data On EMMC!!!


-----------------------------------
Enter "confirm" again to contine!!:
confirm
Do Clean EMMC....

Welcome to fdisk (util-linux 2.38).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

This disk is currently in use - repartitioning is probably a bad idea.
It's recommended to umount all file systems, and swapoff all swap
partitions on this disk.


Command (m for help):
Disk /dev/mmcblk0: 116.5 GiB, 125090922496 bytes, 244318208 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 1EF7AECF-5E73-0544-8B59-C0A103540DFE

Device         Start       End   Sectors   Size Type
/dev/mmcblk0p1  2048 244318174 244316127 116.5G Linux filesystem

Command (m for help): Created a new GPT disklabel (GUID: 884D240F-4C5D-4A42-8E79-C9256F23787B).

Command (m for help): The partition table has been altered.
Failed to remove partition 1 from system: Resource busy

The kernel still uses the old partitions. The new table will be used at the next reboot.
Syncing disks.
```

**Comment by ex3xex** [comment]
Aah my bad, I forget to give permission to execute the script. It's is working now, thanks.
